version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./database-initialization:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
